language: node_js
node_js:
  - 10
env:
  global:
    - SAUCE_USERNAME=$SAUCE_USERNAME
    - SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY
addons:
  sauce_connect: true
branches:
  only:
    - master
before_install:
  - export TZ=America/Denver
  - date
dist: trusty
sudo: false
